---
- name: Install apache webserver and Enable firewall
  hosts: all
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
  - name: start httpd
    service:
      name: httpd
      state: started
#      enabled: true
  - name: add httpd to  firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
